#!/usr/bin/env python3
"""Write a short Mutation tests sticky-comment markdown (Maxframe shape)."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = ROOT / "scripts/ci/mutation-config.json"


def _count(stats: dict[str, object], *keys: str) -> int:
    for key in keys:
        if key in stats and stats[key] is not None:
            return int(stats[key])
    return 0


def build_markdown(
    *,
    profile: str,
    floor: float,
    stats: dict[str, object] | None,
    timeout_minutes: int,
) -> str:
    weekly = "`mutation-full.yml` (explicit critical files, no `cli_tools.py`)"
    header = [
        "## Mutation tests",
        "",
        f"- **Profile:** {profile}",
        "- **Tool:** mutmut (Ubuntu)",
        f"- **Job timeout:** {timeout_minutes} minutes",
        f"- **Strict weekly backstop:** {weekly}",
        "",
    ]
    if stats is None:
        header.extend(
            [
                "Mutation stats JSON was not found (job cancelled, timed out, or mutmut did not finish).",
                "Check the job logs and the uploaded `mutation-reports-*` artifact.",
                "",
                "_Generated by CI mutation job_",
                "",
            ]
        )
        return "\n".join(header)

    killed = _count(stats, "killed")
    survived = _count(stats, "survived")
    timeout = _count(stats, "timeout", "timeouts")
    total = _count(stats, "total")
    denom = killed + survived
    score = (100.0 * killed / denom) if denom else 0.0
    status = (
        f"Passing (>= {floor:.0f})"
        if denom and score >= floor
        else f"Failing (< {floor:.0f})"
        if denom
        else "No scored mutants"
    )
    lines = header + [
        f"- Mutation score: **{score:.2f}%**",
        f"- Threshold: **{floor:.0f}**",
        f"- Status: **{status}**",
        "",
        "| Metric | Count |",
        "|---|---:|",
        f"| Killed | {killed} |",
        f"| Survived | {survived} |",
        f"| Timeout | {timeout} |",
        f"| Total | {total} |",
        "",
        "_Generated from `mutants/mutmut-cicd-stats.json`_",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    parser.add_argument(
        "--stats",
        default=str(ROOT / "mutants/mutmut-cicd-stats.json"),
    )
    parser.add_argument(
        "--profile", default=os.environ.get("AVO_MUTATION_PROFILE", "light")
    )
    args = parser.parse_args()
    config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    spec = config.get(args.profile) or {}
    floor = float(spec.get("min_killed_percent") or 0)
    timeout_minutes = int(spec.get("job_timeout_minutes") or 20)
    stats_path = Path(args.stats)
    stats = None
    if stats_path.is_file():
        stats = json.loads(stats_path.read_text(encoding="utf-8"))
    text = build_markdown(
        profile=args.profile,
        floor=floor,
        stats=stats,
        timeout_minutes=timeout_minutes,
    )
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8", newline="\n")
    summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary:
        with Path(summary).open("a", encoding="utf-8") as handle:
            handle.write(text)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
