#!/usr/bin/env python3
"""Write a short Size Signal sticky-comment (packed size, not a tarball dump)."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def format_bytes(n: int) -> str:
    value = float(n)
    if value >= 1024 * 1024:
        return f"{value / (1024 * 1024):.2f} MB"
    if value >= 1024:
        return f"{value / 1024:.1f} KB"
    return f"{int(value)} B"


def parse_pack_payload(payload: object) -> dict[str, object]:
    item = payload[0] if isinstance(payload, list) and payload else payload
    if not isinstance(item, dict):
        raise ValueError("npm pack JSON was not an object")
    return item


def dir_size_bytes(path: Path) -> int | None:
    if not path.is_dir():
        return None
    total = 0
    for file in path.rglob("*"):
        if file.is_file() and not file.is_symlink():
            try:
                total += file.stat().st_size
            except OSError:
                continue
    return total


def summarize(
    pack: dict[str, object],
    *,
    node_modules_bytes: int | None,
) -> dict[str, str]:
    packed = int(pack.get("size") or 0)
    unpacked = int(pack.get("unpackedSize") or 0)
    files = int(pack.get("entryCount") or 0)
    name = str(pack.get("filename") or pack.get("id") or "package.tgz")
    version = str(pack.get("version") or "")
    summary = {
        "filename": name,
        "version": version,
        "packed": format_bytes(packed),
        "unpacked": format_bytes(unpacked),
        "files": str(files),
        "node_modules": (
            format_bytes(node_modules_bytes)
            if node_modules_bytes is not None
            else "unavailable"
        ),
    }
    return summary


def build_markdown(summary: dict[str, str]) -> str:
    version = f" `{summary['version']}`" if summary.get("version") else ""
    return "\n".join(
        [
            "## Size signal",
            "",
            "- Status: **PASS (informational)**",
            "- Policy: **non-blocking** · not a merge gate",
            f"- Package{version}: `{summary['filename']}`",
            "",
            "| Metric | Value |",
            "|---|---:|",
            f"| Packed tarball | {summary['packed']} |",
            f"| Unpacked publish contents | {summary['unpacked']} |",
            f"| Files in pack | {summary['files']} |",
            f"| `node_modules` (install proxy) | {summary['node_modules']} |",
            "",
            (
                "Packed/unpacked sizes come from `npm pack --dry-run --json`. "
                "No tarball file list — that dump is noise."
            ),
            "",
            "_Generated by `scripts/ci/write_size_signal_report.py`_",
            "",
        ]
    )


def _load_pack_json(path: Path | None) -> dict[str, object]:
    if path and path.is_file():
        return parse_pack_payload(json.loads(path.read_text(encoding="utf-8")))
    proc = subprocess.run(
        ["npm", "pack", "--dry-run", "--json"],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
        env={**os.environ, "NO_COLOR": "1"},
    )
    stdout = (proc.stdout or "").strip()
    if not stdout:
        raise SystemExit(proc.stderr or "npm pack --dry-run --json produced no JSON")
    return parse_pack_payload(json.loads(stdout))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    parser.add_argument("--pack-json", default="")
    args = parser.parse_args()
    pack = _load_pack_json(Path(args.pack_json) if args.pack_json else None)
    node_modules = dir_size_bytes(ROOT / "node_modules")
    text = build_markdown(summarize(pack, node_modules_bytes=node_modules))
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8", newline="\n")
    summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary:
        with Path(summary).open("a", encoding="utf-8") as handle:
            handle.write(text)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
