#!/usr/bin/env python3
"""Write a short Mutation tests sticky-comment markdown (Maxframe shape)."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = ROOT / "scripts/ci/mutation-config.json"


def _count(stats: dict[str, object], *keys: str) -> int:
    for key in keys:
        if key in stats and stats[key] is not None:
            return int(stats[key])
    return 0


def _intro_lines(*, profile: str, timeout_minutes: int) -> list[str]:
    weekly = "`mutation-full.yml` (explicit critical files, no `cli_tools.py`)"
    return [
        "## Mutation tests",
        "",
        f"- **Profile:** {profile}",
        "- **Tool:** mutmut (Ubuntu)",
        f"- **Job timeout:** {timeout_minutes} minutes",
        f"- **Strict weekly backstop:** {weekly}",
        "",
    ]


def stats_for_this_run(
    stats: dict[str, object] | None,
    *,
    sha: str,
    run_id: str,
) -> dict[str, object] | None:
    """Trust stats only when this run stamped them after export.

    A restored ``mutants/`` cache keeps the previous run's killed/survived
    counts. Clean-test failures never reach the stamp, so those counts must
    not become this run's score. Same-commit re-runs use a new workflow run id.
    """
    if not isinstance(stats, dict):
        return None
    sha = sha.strip().lower()
    run_id = run_id.strip()
    if not re.fullmatch(r"[0-9a-f]{40}", sha) or not run_id:
        return None
    stamped_sha = str(stats.get("sha", "")).strip().lower()
    stamped_run = str(stats.get("run_id", "")).strip()
    if stamped_sha != sha or stamped_run != run_id:
        return None
    return stats


def stamp_stats_file(path: Path, *, sha: str, run_id: str) -> dict[str, object]:
    """Record the commit and workflow run that just exported these stats."""
    sha = sha.strip().lower()
    run_id = run_id.strip()
    if not re.fullmatch(r"[0-9a-f]{40}", sha):
        raise ValueError(
            f"refusing to stamp mutation stats without a commit sha: {sha!r}"
        )
    if not run_id:
        raise ValueError("refusing to stamp mutation stats without a workflow run id")
    stats = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(stats, dict):
        raise ValueError("mutation stats JSON must be an object")
    stats["sha"] = sha
    stats["run_id"] = run_id
    path.write_text(
        json.dumps(stats, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return stats


def unscored_markdown(
    *,
    profile: str,
    timeout_minutes: int,
    stats_file_found: bool,
) -> str:
    """Honest sticky when this run never produced a score. No kill rate."""
    lines = _intro_lines(profile=profile, timeout_minutes=timeout_minutes)
    lines.extend(
        [
            "- Mutation score: **did not score**",
            "- Status: **Did not score**",
            "",
            "This run did not score.",
        ]
    )
    if stats_file_found:
        lines.append(
            "Clean tests failed, mutmut did not finish, or the stats file is a "
            "restored cache from another run."
        )
    else:
        lines.append(
            "Mutation stats JSON was not found (job cancelled, timed out, or "
            "mutmut did not finish)."
        )
    lines.extend(
        [
            "Killed and survived counts from another run are not this result.",
            "Check the job logs and the uploaded `mutation-reports-*` artifact.",
            "",
            "_Generated by CI mutation job_",
            "",
        ]
    )
    return "\n".join(lines)


def mutation_metrics_document(
    stats: dict[str, object] | None,
    *,
    sha: str,
    floor: float,
) -> dict | None:
    """SHA-bound killed/survived counts for the release snapshot. No bare score."""
    if not isinstance(stats, dict):
        return None
    if not re.fullmatch(r"[0-9a-f]{40}", sha):
        return None
    killed = stats.get("killed")
    survived = stats.get("survived")
    if type(killed) is not int or type(survived) is not int:
        return None
    if killed < 0 or survived < 0 or killed + survived <= 0:
        return None
    return {
        "sha": sha,
        "killed": killed,
        "survived": survived,
        "floor": floor,
    }


def build_markdown(
    *,
    profile: str,
    floor: float,
    stats: dict[str, object] | None,
    timeout_minutes: int,
) -> str:
    if stats is None:
        return unscored_markdown(
            profile=profile,
            timeout_minutes=timeout_minutes,
            stats_file_found=False,
        )

    header = _intro_lines(profile=profile, timeout_minutes=timeout_minutes)
    killed = _count(stats, "killed")
    survived = _count(stats, "survived")
    timeout = _count(stats, "timeout", "timeouts")
    total = _count(stats, "total")
    denom = killed + survived
    score = (100.0 * killed / denom) if denom else 0.0
    status = (
        f"Passing (>= {floor:.0f})"
        if denom and score >= floor
        else f"Failing (< {floor:.0f})"
        if denom
        else "No scored mutants"
    )
    lines = header + [
        f"- Mutation score: **{score:.2f}%**",
        f"- Threshold: **{floor:.0f}**",
        f"- Status: **{status}**",
        "",
        "| Metric | Count |",
        "|---|---:|",
        f"| Killed | {killed} |",
        f"| Survived | {survived} |",
        f"| Timeout | {timeout} |",
        f"| Total | {total} |",
        "",
        "_Generated from `mutants/mutmut-cicd-stats.json`_",
        "",
    ]
    return "\n".join(lines)


def compose_report(
    stats: dict[str, object] | None,
    *,
    profile: str,
    floor: float,
    timeout_minutes: int,
    sha: str,
    run_id: str,
) -> tuple[str, dict | None]:
    """Sticky markdown plus SHA-bound metrics. Unstamped cache yields neither score."""
    sha = sha.strip().lower()
    run_id = run_id.strip()
    trusted = stats_for_this_run(stats, sha=sha, run_id=run_id)
    if trusted is None:
        text = unscored_markdown(
            profile=profile,
            timeout_minutes=timeout_minutes,
            stats_file_found=stats is not None,
        )
        return text, None
    text = build_markdown(
        profile=profile,
        floor=floor,
        stats=trusted,
        timeout_minutes=timeout_minutes,
    )
    return text, mutation_metrics_document(trusted, sha=sha, floor=floor)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="")
    parser.add_argument(
        "--stamp",
        default="",
        help="Bind exported stats to GITHUB_SHA and GITHUB_RUN_ID",
    )
    parser.add_argument(
        "--stats",
        default=str(ROOT / "mutants/mutmut-cicd-stats.json"),
    )
    parser.add_argument(
        "--profile", default=os.environ.get("AVO_MUTATION_PROFILE", "light")
    )
    args = parser.parse_args(argv)
    sha = os.environ.get("GITHUB_SHA", "").strip().lower()
    run_id = os.environ.get("GITHUB_RUN_ID", "").strip()
    if args.stamp:
        try:
            stamp_stats_file(Path(args.stamp), sha=sha, run_id=run_id)
        except ValueError as exc:
            print(str(exc), file=sys.stderr)
            return 2
        print(f"stamped {args.stamp}")
        return 0
    if not args.out:
        parser.error("--out is required unless --stamp is set")
    config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    spec = config.get(args.profile) or {}
    floor = float(spec.get("min_killed_percent") or 0)
    timeout_minutes = int(spec.get("job_timeout_minutes") or 20)
    stats_path = Path(args.stats)
    stats = None
    if stats_path.is_file():
        stats = json.loads(stats_path.read_text(encoding="utf-8"))
    text, metrics = compose_report(
        stats,
        profile=args.profile,
        floor=floor,
        timeout_minutes=timeout_minutes,
        sha=sha,
        run_id=run_id,
    )
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8", newline="\n")
    metrics_path = out.parent / "mutation-metrics.json"
    if metrics is None:
        if metrics_path.is_file():
            metrics_path.unlink()
    else:
        metrics_path.write_text(
            json.dumps(metrics, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
            newline="\n",
        )
    summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary:
        with Path(summary).open("a", encoding="utf-8") as handle:
            handle.write(text)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
